name: "bmi088"
# i2c_bus serial number
i2c_bus: 1
# accelerometer range, unit 'g'
acc_range: 12
# gyroscope range, unit 'deg/s'
gyro_range: 1000
# accelerometer low pass filter bandwidth
acc_bandwidth: 40
# gyroscope low pass filter bandwidth
gyro_bandwidth: 40
# group_delay of imu,
# which means the latency of the motion of body to data ready, unit 'ms'
group_delay: 7
